"""A governed proposition whose subject is EVIDENCE, not economics.

WHY A SECOND KIND RATHER THAN A WIDER FIRST ONE. `financial_proposition`
answers "is this economic statement still true?" by rebuilding the statement
from authoritative order state. A classification of historically unverifiable
tax says the opposite: the economics CANNOT be established. Routing it through
the economic verifier would ask the one question whose answer is already known
to be no, and that refusal would be the economic control working rather than a
defect in it. So `financial_proposition` is left exactly as it is and this
module borrows its four disciplines -- a closed field set, fixed-scale value
canonicalisation, domain separation, and version pinning. Only the field list,
the domain string and the rebuild rule differ.

THE ONE NEW SEMANTIC RULE, stated so that no other is smuggled in beside it:

    A classification proposition is a governed evidence proposition whose
    validity consists of internal target-set integrity plus live-set equality,
    rather than reconstruction of historical economics.

Everything else -- canonicalisation, closed fields, domain separation,
versioning, constant-time comparison, the fresh re-read before execution,
fail-closed dispatch, independent verification -- is inherited machinery.

WHAT "REBUILD" MEANS HERE. There is no figure to recompute. What is recomputed
is the TARGET SET IDENTITY: the two sorted order-id arrays are re-fingerprinted
and the census id re-derived from them, so a proposition whose arrays were
edited fails on its own internal consistency before any live state is read. The
live census is then compared to the approved one to detect drift. It never
replaces it.

THE CENSUS PREDICATE IS DEFINED ONCE, HERE. There was no canonical
implementation to reuse: searched for one and the population is computed nowhere
in the repository or the database. So `_CENSUS_SQL` is new code, and its warrant
is stated rather than assumed -- it replicates the precedence of the DEPLOYED
`trgfn_invoice_before` (order billing address -> account default billing ->
contact default billing -> literal CA/ON), validated fragment by fragment
against `pg_proc`, and reproducing the same partition across eight independent
measurements. Because it is new code rather than a reused contract, it must have
exactly one definition: this one. The manifest that an approval carries is
generated by `build()` below, and execution-time drift detection uses the same
`measure_census()`. The independent verifier deliberately does NOT call either
-- it compares the carrier against the frozen manifest, which is what keeps it
independent.
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Dict, Tuple

from app.core.financial_proposition import hashes_match   # constant-time; reused

# Distinct from conscestra.financial_proposition.v1 by construction: a
# classification digest must not be presentable where an economic one is
# expected, and vice versa.
_DOMAIN = "conscestra.classification_proposition.v1"
PROPOSITION_VERSION = 1

# The marker the governance dispatcher reads. It lives INSIDE the closed field
# set, so a proposition cannot claim this kind without carrying every field the
# kind requires, and cannot carry the marker without being hashed under it.
KIND = "classification.v1"

# The assertion this kind authorises. Fixed here rather than taken from the
# caller: a capability that could assert any state would be a different, wider
# capability than the one that was approved.
ASSERTION_TYPE = "economic_correctness"
ASSERTION_STATE = "historically_unverified"
ASSERTION_RULE = "no_evidence"
MECHANISM_VERSION = "classification.economic_correctness.1"

DECLARED_FIELDS: Tuple[str, ...] = (
    "proposition_kind", "census_id",
    "fingerprint_all", "fingerprint_zero_tax", "fingerprint_nonzero_unresolved",
    "count_all", "count_zero_tax", "count_nonzero_unresolved",
    "zero_tax_order_ids", "nonzero_unresolved_order_ids",
    "assertion_type", "state", "rule", "mechanism_version",
)
PROPOSITION_FIELDS: Tuple[str, ...] = (
    ("approval_uuid", "action_type") + DECLARED_FIELDS)


class PropositionBlocked(Exception):
    """A required fact is not established. Carries every reason rather than the
    first, so an operator sees the whole gap in one pass."""

    def __init__(self, reasons):
        self.reasons = list(reasons)
        super().__init__("; ".join(self.reasons))


# ---- canonical form: the same disciplines as the economic module ------------

def _canon_value(v: Any) -> Any:
    if v is None:
        return None
    if isinstance(v, bool):
        # Before the int branch: bool is a subclass of int, so True would
        # otherwise canonicalise as 1 and become indistinguishable from it.
        return v
    if isinstance(v, int):
        return int(v)
    if isinstance(v, (float, Decimal)):
        # EVERY NUMBER IN THIS FIELD SET IS A COUNT, so the canonical form is
        # the integer -- not a fixed-scale string as in the economic module,
        # which carries money. Returning a string here reproduced exactly the
        # bug MONEY_FIELDS documents: 195 canonicalised as the number 195 and
        # 195.0 as the string "195", so two identical propositions hashed
        # differently. Caught by the parity test, which is why it exists.
        return int(Decimal(str(v)).quantize(Decimal(1)))
    if isinstance(v, (list, tuple)):
        return [_canon_value(x) for x in v]
    return str(v)


def canonical(proposition: Dict[str, Any]) -> str:
    """The exact bytes that are hashed.

    Refuses omissions AND additions. A field the proposer added is either
    material -- in which case the field set is wrong -- or it is noise that
    must not reach an approval record.
    """
    missing = [f for f in PROPOSITION_FIELDS if f not in proposition]
    if missing:
        raise ValueError(f"proposition is missing declared fields: {missing}")
    extra = [k for k in proposition if k not in PROPOSITION_FIELDS]
    if extra:
        raise ValueError(f"proposition carries undeclared fields: {extra}")
    canon = {f: _canon_value(proposition[f]) for f in PROPOSITION_FIELDS}
    canon["_v"] = PROPOSITION_VERSION
    return json.dumps(canon, sort_keys=True, separators=(",", ":"))


def proposition_hash(proposition: Dict[str, Any]) -> str:
    """SHA-256 over the domain-separated canonical form.

    Deliberately NOT a hash of the stored jsonb. Measured: the same document
    round-tripped through `::jsonb::text` changes length and digest, because
    jsonb applies its own key ordering and number formatting. Hashing a
    canonical PROJECTION makes the digest independent of how the document was
    stored or transported.
    """
    return hashlib.sha256(
        (_DOMAIN + "|" + canonical(proposition)).encode("utf-8")).hexdigest()


def fingerprint(order_ids) -> str:
    """SHA-256 over newline-joined SORTED order ids.

    Computed from a sorted list of text, never from a serialised document, so
    no JSON or JSONB encoder can change it.
    """
    ids = sorted(str(x) for x in order_ids)
    return hashlib.sha256(("\n".join(ids) + "\n").encode("utf-8")).hexdigest()


def census_id_of(fp_all: str, fp_a: str, fp_b: str) -> str:
    """The census identity: first 32 hex of the digest over the triple.

    TRUNCATION IS DELIBERATE AND RECORDED. 128 bits is the OPERATIONAL
    idempotence key -- the value the guard looks up. It is never the acceptance
    test: acceptance requires all three FULL fingerprints and the full
    proposition hash to match, so a colliding census id would still be refused.
    """
    return hashlib.sha256(
        (fp_all + "|" + fp_a + "|" + fp_b).encode("utf-8")).hexdigest()[:32]


# ---- the census, defined once ----------------------------------------------

# Replicates the precedence of the DEPLOYED trgfn_invoice_before, sections 4
# and 7: the order's billing address, then the account's default billing
# address, then the contact's, then the literal CA/ON fallback. An address
# whose country is the empty string is NOT NULL and therefore short-circuits
# the chain -- that behaviour is part of the deployed contract and is preserved
# here rather than tidied away.
#
# Returns one row per LIVE invoice for which NO active tax_rates row matches the
# resolved jurisdiction: (order_id, is_nonzero_tax).
_CENSUS_SQL = """
WITH base AS (
    SELECT i.invoice_id, i.order_id, i.account_id, i.contact_id, i.tax_amount,
           o.billing_address_id
      FROM invoices i
      LEFT JOIN orders o ON o.order_id = i.order_id
     WHERE COALESCE(i.is_deleted, false) = false
), s1 AS (
    SELECT b.*, a.country AS c1, a.province AS r1
      FROM base b
      LEFT JOIN addresses a ON a.address_id = b.billing_address_id
), s2 AS (
    SELECT s1.*, x.country AS c2, x.province AS r2
      FROM s1
      LEFT JOIN LATERAL (
          SELECT country, province FROM addresses
           WHERE parent_type = 'account' AND parent_id = s1.account_id
             AND is_default = true AND label = 'billing'
             AND s1.c1 IS NULL
           LIMIT 1) x ON true
), s3 AS (
    SELECT s2.*, y.country AS c3, y.province AS r3
      FROM s2
      LEFT JOIN LATERAL (
          SELECT country, province FROM addresses
           WHERE parent_type = 'contact' AND parent_id = s2.contact_id
             AND is_default = true AND label = 'billing'
             AND s2.c1 IS NULL AND s2.c2 IS NULL
           LIMIT 1) y ON true
), res AS (
    SELECT s3.*,
           CASE WHEN c1 IS NOT NULL THEN c1 WHEN c2 IS NOT NULL THEN c2
                WHEN c3 IS NOT NULL THEN c3 ELSE 'CA' END AS jur_country,
           CASE WHEN c1 IS NOT NULL THEN r1 WHEN c2 IS NOT NULL THEN r2
                WHEN c3 IS NOT NULL THEN r3 ELSE 'ON' END AS jur_region,
           CASE WHEN c1 IS NOT NULL THEN 'order_billing_address'
                WHEN c2 IS NOT NULL THEN 'account_default_billing'
                WHEN c3 IS NOT NULL THEN 'contact_default_billing'
                ELSE 'fallback' END AS jur_source
      FROM s3
), rated AS (
    SELECT res.*, tr.n AS rate_rows
      FROM res
      LEFT JOIN LATERAL (
          SELECT count(*) AS n FROM tax_rates t
           WHERE t.country = res.jur_country
             AND t.region  = res.jur_region
             AND t.valid_to IS NULL) tr ON true
)
SELECT order_id::text,
       (COALESCE(tax_amount, 0) > 0) AS is_nonzero_tax,
       jur_country, jur_region, jur_source, COALESCE(tax_amount, 0)::text
  FROM rated
 WHERE rate_rows = 0 AND order_id IS NOT NULL
"""


def measure_census(cur) -> Dict[str, Any]:
    """Measure the live population. SELECT ONLY.

    The caller rolls back, which makes read-only structural rather than a
    promise -- the discipline `_verify_proposition_unchanged` already applies to
    the economic verifier.
    """
    cur.execute(_CENSUS_SQL)
    rows = cur.fetchall()
    a = sorted(str(r[0]) for r in rows if not r[1])
    b = sorted(str(r[0]) for r in rows if r[1])
    detail = {str(r[0]): {"resolved_country": r[2], "resolved_region": r[3],
                          "resolution_source": r[4], "recorded_tax_amount": r[5]}
              for r in rows}
    fp_a, fp_b = fingerprint(a), fingerprint(b)
    fp_all = fingerprint(a + b)
    return {"census_id": census_id_of(fp_all, fp_a, fp_b),
            "fingerprint_all": fp_all,
            "fingerprint_zero_tax": fp_a,
            "fingerprint_nonzero_unresolved": fp_b,
            "count_all": len(a) + len(b),
            "count_zero_tax": len(a),
            "count_nonzero_unresolved": len(b),
            "zero_tax_order_ids": a,
            "nonzero_unresolved_order_ids": b,
            "detail": detail}


def build(cur, approval_uuid: str, action_type: str) -> Dict[str, Any]:
    """Construct the proposition from a live measurement.

    This is what generates the artifact an approval carries, so the approved
    manifest and the execution-time drift check share one implementation by
    construction rather than by review.
    """
    m = measure_census(cur)
    if m["count_all"] == 0:
        raise PropositionBlocked(
            ["no invoice resolves to an unmatched tax jurisdiction; there is "
             "nothing to classify"])
    if set(m["zero_tax_order_ids"]) & set(m["nonzero_unresolved_order_ids"]):
        raise PropositionBlocked(["the two populations overlap"])
    return {
        "approval_uuid": approval_uuid,
        "action_type": action_type,
        "proposition_kind": KIND,
        "census_id": m["census_id"],
        "fingerprint_all": m["fingerprint_all"],
        "fingerprint_zero_tax": m["fingerprint_zero_tax"],
        "fingerprint_nonzero_unresolved": m["fingerprint_nonzero_unresolved"],
        "count_all": m["count_all"],
        "count_zero_tax": m["count_zero_tax"],
        "count_nonzero_unresolved": m["count_nonzero_unresolved"],
        "zero_tax_order_ids": m["zero_tax_order_ids"],
        "nonzero_unresolved_order_ids": m["nonzero_unresolved_order_ids"],
        "assertion_type": ASSERTION_TYPE,
        "state": ASSERTION_STATE,
        "rule": ASSERTION_RULE,
        "mechanism_version": MECHANISM_VERSION,
    }


def rebuild_and_compare(cur, stored: Dict[str, Any],
                        stored_hash: str) -> Dict[str, Any]:
    """{ok, reason, rebuilt_hash}. Same signature as the economic verifier.

    THREE INDEPENDENT REFUSALS, each able to stop execution on its own:

      1. internal consistency -- the declared fingerprints, counts and census
         id must follow from the declared order-id arrays. A proposition whose
         arrays were edited fails here, before any live state is consulted.
      2. authorisation binding -- the rehash must equal what was approved.
      3. live drift -- the census measured now must equal the approved census.
         This is the control that makes "approved equals executed" true rather
         than asserted.
    """
    missing = [f for f in PROPOSITION_FIELDS if f not in stored]
    if missing:
        return {"ok": False, "rebuilt_hash": None,
                "reason": f"the stored proposition is not a complete "
                          f"classification proposition (missing "
                          f"{', '.join(missing[:6])}); it cannot be verified "
                          f"against current state"}
    if str(stored.get("proposition_kind")) != KIND:
        return {"ok": False, "rebuilt_hash": None,
                "reason": f"this verifier handles {KIND!r}, not "
                          f"{stored.get('proposition_kind')!r}"}
    for fld, want in (("assertion_type", ASSERTION_TYPE),
                      ("state", ASSERTION_STATE), ("rule", ASSERTION_RULE)):
        if str(stored.get(fld)) != want:
            return {"ok": False, "rebuilt_hash": None,
                    "reason": f"this capability asserts {fld}={want!r}; the "
                              f"proposition declares {stored.get(fld)!r}"}

    a = list(stored.get("zero_tax_order_ids") or [])
    b = list(stored.get("nonzero_unresolved_order_ids") or [])
    reasons = []
    if set(a) & set(b):
        reasons.append("the two populations overlap")
    if len(a) != len(set(a)) or len(b) != len(set(b)):
        reasons.append("a population contains duplicate order ids")
    fp_a, fp_b = fingerprint(a), fingerprint(b)
    fp_all = fingerprint(a + b)
    if fp_a != stored.get("fingerprint_zero_tax"):
        reasons.append("fingerprint_zero_tax does not match its order ids")
    if fp_b != stored.get("fingerprint_nonzero_unresolved"):
        reasons.append("fingerprint_nonzero_unresolved does not match its order ids")
    if fp_all != stored.get("fingerprint_all"):
        reasons.append("fingerprint_all does not match the union")
    if census_id_of(fp_all, fp_a, fp_b) != stored.get("census_id"):
        reasons.append("census_id is not derived from the declared fingerprints")
    for fld, n in (("count_zero_tax", len(a)),
                   ("count_nonzero_unresolved", len(b)),
                   ("count_all", len(a) + len(b))):
        v = stored.get(fld)
        if v is None or int(v) != n:
            reasons.append(f"{fld} disagrees with its order ids")
    if reasons:
        return {"ok": False, "rebuilt_hash": None,
                "reason": "the proposition is internally inconsistent: "
                          + "; ".join(reasons)}

    rebuilt = {f: stored.get(f) for f in PROPOSITION_FIELDS}
    rebuilt_hash = proposition_hash(rebuilt)
    if not hashes_match(rebuilt_hash, stored_hash):
        return {"ok": False, "rebuilt_hash": rebuilt_hash,
                "reason": "the proposition hash does not match the approved "
                          "authorisation; the approval does not cover this "
                          "proposition"}

    live = measure_census(cur)
    if live["census_id"] != stored.get("census_id"):
        return {"ok": False, "rebuilt_hash": rebuilt_hash,
                "reason": f"the population has changed since approval "
                          f"(approved census {stored.get('census_id')}, "
                          f"measured {live['census_id']}); the approved "
                          f"authorisation does not cover it"}
    return {"ok": True, "rebuilt_hash": rebuilt_hash, "reason": "unchanged"}


# ---- the carrier contract --------------------------------------------------

# SERIALISE SAME-CENSUS EXECUTION BEFORE THE IDEMPOTENCE CHECK IS EVALUATED.
#
# Measured, not assumed: under READ COMMITTED two concurrent transactions BOTH
# evaluate the NOT EXISTS below as true, because neither can see the other's
# uncommitted row, and BOTH insert -- two assertions for one (order, census) in
# an append-only table, where they could never be removed. A sequential replay
# test passes and says nothing about this.
#
# The lock makes the second execution wait, see the committed row, and insert
# zero. `trgfn_order_assertion_guard` already takes an advisory lock on this
# very table for the same reason -- same key shape, same reason.
ADVISORY_LOCK_SQL = "SELECT pg_advisory_xact_lock(hashtextextended(%(cid)s, 0))"

# The ONLY statement this capability may execute against production. One table,
# INSERT only, no dynamic SQL, no caller-supplied identifier.
ASSERT_INSERT_SQL = """
INSERT INTO order_financial_assertions
    (order_id, assertion_type, state, rule, evidence, asserted_by)
SELECT %(oid)s::uuid, %(atype)s, %(state)s, %(rule)s, %(ev)s::jsonb, %(by)s
 WHERE NOT EXISTS (
       SELECT 1 FROM order_financial_assertions a
        WHERE a.order_id = %(oid)s::uuid
          AND a.assertion_type = %(atype)s
          AND a.evidence -> 'census' ->> 'census_id' = %(cid)s)
"""


def build_evidence(prop: Dict[str, Any], order_id: str, population: str,
                   detail: Dict[str, Any], asserter: Dict[str, Any]) -> str:
    """The evidence payload, as JSON text.

    WHAT IS KNOWN AND WHAT IS NOT ARE BOTH NAMED, and the current jurisdiction
    sits under `current_state` with a disclaimer, so nothing in this payload can
    be read as the historical determination. `not_asserted` names the stronger
    conclusions the evidence does NOT support, because an assertion that leaves
    them unstated invites a reader to supply them.
    """
    is_nonzero = population == "nonzero_unresolved"
    established = [
        "the recorded tax amount is as stated under current_state",
        "no active tax_rates row matched the resolved jurisdiction at "
        "measurement time",
        "the historical tax determination is not reconstructable from "
        "surviving evidence",
    ]
    unknown = [
        "the jurisdiction that resolved at invoice time",
        "which tax_rates row, if any, was matched",
        "the determination timestamp",
        "whether any tax treatment was ever established",
    ]
    not_asserted = [
        "that the invoice is tax-exempt",
        "that the tax outcome was correct",
        "that the tax outcome was incorrect",
        "that zero tax was authorised",
        "that Canada maps to CA",
        "any Mexican tax treatment",
    ]
    if is_nonzero:
        established += [
            "the recorded tax amount is non-zero",
            "no recoverable determination supports that figure",
        ]
        unknown += ["the source, actor and timestamp that produced the figure"]
        not_asserted += [
            "that any identified caller, employee or system supplied the rate",
        ]
    return json.dumps({
        "census": {
            "census_id": prop["census_id"],
            "fingerprint_all": prop["fingerprint_all"],
            "population": population,
            "predicate": "deployed trgfn_invoice_before precedence; zero "
                         "active tax_rates rows matched",
            "measured_at": datetime.now(timezone.utc).isoformat(
                timespec="seconds"),
        },
        "established": established,
        "unknown": unknown,
        "current_state": dict(
            detail.get(order_id) or {},
            note="CURRENT values, recorded for reproducibility only. These are "
                 "NOT the historical determination and must not be read as one.",
            matching_active_rate_rows=0),
        "not_asserted": not_asserted,
        "asserter": asserter,
        "mechanism_version": prop["mechanism_version"],
    }, default=str)
