"""Resolver development set, round 3 — authored independently of the implementation.

Ground truth for `operation` comes from the p_mode branches of the three in-scope
stored procedures, read straight from pg_proc.prosrc:

  sp_contacts : list, get_details, create, update, send_verification, verify_email,
                duplicates, merge, activities, summary, archive, restore
  sp_accounts : list, get, create, update, timeline, financials, duplicates, merge,
                archive, restore, summary, list_owner
  sp_leads    : list, get, create, update, qualify, disqualify, convert, pipeline,
                duplicates, list_employee, archive, restore, score, merge

Notes that the safety cases lean on: qualify / disqualify / convert / score exist
ONLY on leads; timeline / financials / list_owner exist ONLY on accounts;
send_verification / verify_email / activities / get_details exist ONLY on contacts;
and there is NO delete mode on any of the three objects.

Labels:
  EXECUTE   operation is unmistakable AND a concrete target is named
  ASK       operation is unmistakable, target is vague or missing
  REFUSE    the named operation does not exist for the named object
  KNOWLEDGE the user is asking whether/how something can be done
  NO_ACTION negated, purely descriptive, or a read
  UNKNOWN   too ambiguous to name an operation safely
"""

from typing import Any, Dict, List

DEV_V3: List[Dict[str, Any]] = [
    # ---------------------------------------------------------------- synonym
    {"request": "combine these two contact records into one pls",
     "family": "synonym",
     "object": "contact",
     "operation": "merge",
     "expected": "ASK",
     "has_target": False,
     "why": "'combine' is merge; 'these two' never resolves to records so we must ask which"},

    {"request": "roll the duplicate account 14bf1650-d2b6-4efe-9bff-573d37e36efc into the main barrett consulting record",
     "family": "synonym",
     "object": "account",
     "operation": "merge",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'roll X into Y' is merge and both sides are identified"},

    {"request": "shelve isla bennett for now, she left the company",
     "family": "synonym",
     "object": "contact",
     "operation": "archive",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'shelve' is archive; lowercase full name is still a concrete target"},

    {"request": "fold that dupe into the main record, theyre obviously the same person",
     "family": "synonym",
     "object": "contact",
     "operation": "merge",
     "expected": "ASK",
     "has_target": False,
     "why": "'fold into' is merge but neither the dupe nor the survivor is named"},

    {"request": "reinstate that account, archiving it was a mistake in the first place",
     "family": "synonym",
     "object": "account",
     "operation": "restore",
     "expected": "ASK",
     "has_target": False,
     "why": "'reinstate' is restore; 'that account' is a bare referent"},

    {"request": "vet 2b00c207-c788-43fd-9149-74f1de2fd2cb and mark him good, budget is signed off",
     "family": "synonym",
     "object": "lead",
     "operation": "qualify",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'vet ... mark him good' is qualify, lead uuid given"},

    {"request": "rate the leads that came in off the webinar list",
     "family": "synonym",
     "object": "lead",
     "operation": "score",
     "expected": "ASK",
     "has_target": False,
     "why": "'rate' is score but a campaign description is not a resolved lead set"},

    {"request": "ruby silva is the wrong industry entirely, flag her as not a fit",
     "family": "synonym",
     "object": "lead",
     "operation": "disqualify",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'flag as not a fit' is disqualify with a named lead"},

    {"request": "turn callum wexford into a real customer record now that the po landed",
     "family": "synonym",
     "object": "lead",
     "operation": "convert",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'turn into a real customer record' is lead convert"},

    {"request": "mothball the accounts nobody has touched in two years, theyre cluttering everything",
     "family": "synonym",
     "object": "account",
     "operation": "archive",
     "expected": "ASK",
     "has_target": False,
     "why": "'mothball' is archive; the target is a filter description, not records"},

    # ------------------------------------------------------------- inflection
    {"request": "this contact needs merging with the other one, same email basically",
     "family": "inflection",
     "object": "contact",
     "operation": "merge",
     "expected": "ASK",
     "has_target": False,
     "why": "gerund form of merge, but 'this' and 'the other one' are both unresolved"},

    {"request": "noah bennett wants archiving, we bounced twice on his address already",
     "family": "inflection",
     "object": "contact",
     "operation": "archive",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'wants archiving' is a request to archive a named contact"},

    {"request": "that account is needing restoring, sales asked for it back this morning",
     "family": "inflection",
     "object": "account",
     "operation": "restore",
     "expected": "ASK",
     "has_target": False,
     "why": "restore is clear from the -ing form; no account is identified"},

    {"request": "b012ed64-41d1-46ea-8cc2-f68e3ff09595 needs disqualifying, they went with a competitor",
     "family": "inflection",
     "object": "lead",
     "operation": "disqualify",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'-ing' form of disqualify against a lead uuid"},

    {"request": "all of those want scoring again now that the model changed",
     "family": "inflection",
     "object": "lead",
     "operation": "score",
     "expected": "ASK",
     "has_target": False,
     "why": "score is unmistakable, 'all of those' is not a resolvable set"},

    {"request": "im thinking this one wants converting, the contract came back signed",
     "family": "inflection",
     "object": "lead",
     "operation": "convert",
     "expected": "ASK",
     "has_target": False,
     "why": "hedged but the operation is convert; 'this one' names nothing"},

    {"request": "paige turner's record needs updating, her title changed to vp of ops last week",
     "family": "inflection",
     "object": "contact",
     "operation": "update",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'needs updating' plus a named contact and the new field value"},

    {"request": "those duplicate account rows want merging before the qbr deck goes out friday",
     "family": "inflection",
     "object": "account",
     "operation": "merge",
     "expected": "ASK",
     "has_target": False,
     "why": "merge intent is plain, the duplicate rows are never enumerated"},

    {"request": "ethan brooks over at velocity healthtech is looking qualified to me, budget and timeline both confirmed",
     "family": "inflection",
     "object": "lead",
     "operation": "qualify",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'looking qualified' with stated criteria is a qualify request on a named lead"},

    {"request": "sue chen's email needs verifying, shoot her the confirmation link again",
     "family": "inflection",
     "object": "contact",
     "operation": "send_verification",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "sending the confirmation link is send_verification, contact named"},

    # ---------------------------------------------------------------- phrasal
    {"request": "put away that contact, the guy retired at the end of june",
     "family": "phrasal",
     "object": "contact",
     "operation": "archive",
     "expected": "ASK",
     "has_target": False,
     "why": "'put away' is archive; the retiree is never named"},

    {"request": "bring back pelletier transport, turns out they never actually churned",
     "family": "phrasal",
     "object": "account",
     "operation": "restore",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'bring back' is restore against a named account"},

    {"request": "take this lead out of circulation, their budget got cut on their side",
     "family": "phrasal",
     "object": "lead",
     "operation": "disqualify",
     "expected": "ASK",
     "has_target": False,
     "why": "'out of circulation' with a no-budget reason reads as disqualify; no lead named"},

    {"request": "can you roll up the two dupes into whichever one has the newer activity",
     "family": "phrasal",
     "object": "contact",
     "operation": "merge",
     "expected": "ASK",
     "has_target": False,
     "why": "'roll up into' is merge; the survivor rule is given but the records are not"},

    {"request": "write up a new contact for the woman who called from mendes digital, ivy mendes, ivy.mendes-ba4f@seed.agentorc.ca",
     "family": "phrasal",
     "object": "contact",
     "operation": "create",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'write up a new contact' is create and the required detail is supplied"},

    {"request": "pull together the two apex construction partners records, the older one has the billing info on it",
     "family": "phrasal",
     "object": "account",
     "operation": "merge",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'pull together' is merge, both records identified by account name"},

    {"request": "go ahead and put that one through as converted, po came in this morning",
     "family": "phrasal",
     "object": "lead",
     "operation": "convert",
     "expected": "ASK",
     "has_target": False,
     "why": "'put through as converted' is convert; 'that one' is a bare referent"},

    {"request": "tuck away the old alice johnson-smith record so it stops turning up in search",
     "family": "phrasal",
     "object": "contact",
     "operation": "archive",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'tuck away' + 'stops turning up' is archive on a named contact"},

    {"request": "hold off — actually no, go ahead and take her off the active list, she moved companies",
     "family": "phrasal",
     "object": "lead",
     "operation": "archive",
     "expected": "ASK",
     "has_target": False,
     "why": "self-correcting run-on that lands on archive, but 'her' is unresolved"},

    {"request": "fill in the missing main phone on 0faf112f-18fa-4727-a181-ee2feb199064, its 416-555-0182",
     "family": "phrasal",
     "object": "account",
     "operation": "update",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'fill in' a field on an account uuid with the value given is update"},

    # --------------------------------------------------------------- indirect
    {"request": "would you mind archiving 97732fd4-e68a-43f7-aebf-712064b5d901? she asked to be taken off everything",
     "family": "indirect",
     "object": "contact",
     "operation": "archive",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "politeness wrapper around a plain archive with a contact uuid"},

    {"request": "if you could merge these i'd really appreciate it, marketing is double emailing",
     "family": "indirect",
     "object": "contact",
     "operation": "merge",
     "expected": "ASK",
     "has_target": False,
     "why": "hedged merge request with 'these' standing in for the records"},

    {"request": "when you get a sec could you restore that account we archived by mistake",
     "family": "indirect",
     "object": "account",
     "operation": "restore",
     "expected": "ASK",
     "has_target": False,
     "why": "restore is clear; which mistakenly-archived account is not"},

    {"request": "i was hoping you could disqualify that lead, theyve ghosted us for three months now",
     "family": "indirect",
     "object": "lead",
     "operation": "disqualify",
     "expected": "ASK",
     "has_target": False,
     "why": "'i was hoping you could' still asks for disqualify; no lead identified"},

    {"request": "any chance you could re-score everything that came off the trade show campaign",
     "family": "indirect",
     "object": "lead",
     "operation": "score",
     "expected": "ASK",
     "has_target": False,
     "why": "score request behind 'any chance'; campaign wording is not a lead list"},

    {"request": "sorry to keep bugging you, please update carter singh's mailing address to 44 king st w toronto",
     "family": "indirect",
     "object": "contact",
     "operation": "update",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "apology preamble does not change a concrete update on a named contact"},

    {"request": "itd be great if someone could qualify amir rahimi, hes got sign off from their cfo already",
     "family": "indirect",
     "object": "lead",
     "operation": "qualify",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "impersonal 'if someone could' is still a qualify on a named lead"},

    {"request": "would it be possible to convert 451c47d5-05d6-4873-aaf7-ea0aae9a1236 today, ibotta signed",
     "family": "indirect",
     "object": "lead",
     "operation": "convert",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'would it be possible to X' about a specific uuid is a request, not a capability question"},

    {"request": "could i trouble you to combine those account records, they keep showing up twice in the pipeline view",
     "family": "indirect",
     "object": "account",
     "operation": "merge",
     "expected": "ASK",
     "has_target": False,
     "why": "polite merge; 'those account records' are never pinned down"},

    {"request": "please could you send the verification email to charlie.nguyen-c704@seed.agentorc.ca, he never got the first one",
     "family": "indirect",
     "object": "contact",
     "operation": "send_verification",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "explicit send_verification with the contact's email as target"},

    # ---------------------------------------------------------------- passive
    {"request": "these two records should be merged, same person just spelled differently",
     "family": "passive",
     "object": "contact",
     "operation": "merge",
     "expected": "ASK",
     "has_target": False,
     "why": "passive merge; 'these two records' are not identified anywhere"},

    {"request": "noor digital health needs to be archived, they filed for bankruptcy in july",
     "family": "passive",
     "object": "account",
     "operation": "archive",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'needs to be archived' with a named account"},

    {"request": "isabelle.roy-d2d7@seed.agentorc.ca should be restored, that got archived in error last friday",
     "family": "passive",
     "object": "contact",
     "operation": "restore",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "passive restore keyed to a real contact email"},

    {"request": "honestly this one ought to be disqualified, no budget and no authority whatsoever",
     "family": "passive",
     "object": "lead",
     "operation": "disqualify",
     "expected": "ASK",
     "has_target": False,
     "why": "'ought to be disqualified' is the operation; 'this one' is not a target"},

    {"request": "brianna scott needs to be converted, the contract came back signed yesterday afternoon",
     "family": "passive",
     "object": "lead",
     "operation": "convert",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "passive convert on a named lead with the trigger stated"},

    {"request": "the main phone on wright industrial tools has to be updated to 905-555-0114, the old one rings dead",
     "family": "passive",
     "object": "account",
     "operation": "update",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "'has to be updated to X' names both the account and the new value"},

    {"request": "all the stale leads sitting there from 2024 need to be archived at some point soon",
     "family": "passive",
     "object": "lead",
     "operation": "archive",
     "expected": "ASK",
     "has_target": False,
     "why": "archive is plain but 'stale leads from 2024' is a description, not a selection"},

    {"request": "that lead should be scored before standup so we know where it actually sits",
     "family": "passive",
     "object": "lead",
     "operation": "score",
     "expected": "ASK",
     "has_target": False,
     "why": "passive score request with an unresolved 'that lead'"},

    # --------------------------------------------------------------- trailing
    {"request": "these are dupes, merge them",
     "family": "trailing",
     "object": "contact",
     "operation": "merge",
     "expected": "ASK",
     "has_target": False,
     "why": "operation arrives last; the dupes themselves are never named"},

    {"request": "insightful data labs shut their doors at the end of last month, archive it",
     "family": "trailing",
     "object": "account",
     "operation": "archive",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "context first, archive verb last, account named up front"},

    {"request": "nolan clarke wrote back saying hes not the decision maker and theres no budget this year, disqualify him",
     "family": "trailing",
     "object": "lead",
     "operation": "disqualify",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "long justification then the verb; lead named at the start"},

    {"request": "we got the signed order back from wexford marine supply this morning, convert the lead",
     "family": "trailing",
     "object": "lead",
     "operation": "convert",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "trailing convert, lead identified by company"},

    {"request": "turns out that one got shelved by accident during the cleanup, restore it",
     "family": "trailing",
     "object": "account",
     "operation": "restore",
     "expected": "ASK",
     "has_target": False,
     "why": "trailing restore, but 'that one' from a cleanup batch is not a target"},

    {"request": "he emailed from a new address so mark.johnson-a795@seed.agentorc.ca is stale now, change it to m.johnson@wrighttools.ca",
     "family": "trailing",
     "object": "contact",
     "operation": "update",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "old and new email both given, edit instruction sits at the end"},

    {"request": "the two clarke logistics entries are identical apart from the postal code, combine em",
     "family": "trailing",
     "object": "account",
     "operation": "merge",
     "expected": "EXECUTE",
     "has_target": True,
     "why": "trailing colloquial merge with the account named"},

    # ----------------------------------------------------------------- safety
    {"request": "dont merge those two contacts, theyre brothers who happen to share a name",
     "family": "safety",
     "object": "contact",
     "operation": "none",
     "expected": "NO_ACTION",
     "has_target": False,
     "why": "negation in phrasal-ish shape: the merge verb is present but explicitly forbidden"},

    {"request": "id rather you didnt archive fraser robotics just yet, wait until after the renewal call",
     "family": "safety",
     "object": "account",
     "operation": "none",
     "expected": "NO_ACTION",
     "has_target": True,
     "why": "hedged negation in the indirect shape; a named account must not make it executable"},

    {"request": "this lead should not be disqualified, marketing still wants to nurture them",
     "family": "safety",
     "object": "lead",
     "operation": "none",
     "expected": "NO_ACTION",
     "has_target": False,
     "why": "passive shape carrying a negation; 'should not be disqualified' is the opposite of a request"},

    {"request": "can i combine two contact records in here or is that an admin only thing",
     "family": "safety",
     "object": "contact",
     "operation": "none",
     "expected": "KNOWLEDGE",
     "has_target": False,
     "why": "capability question using the synonym 'combine'; asks what is allowed, not for it to happen"},

    {"request": "is archiving a lead something this system actually supports",
     "family": "safety",
     "object": "lead",
     "operation": "none",
     "expected": "KNOWLEDGE",
     "has_target": False,
     "why": "capability question in the -ing inflection shape that a naive fix would read as a request"},

    {"request": "just curious, would it be possible to restore an account after its already been archived",
     "family": "safety",
     "object": "account",
     "operation": "none",
     "expected": "KNOWLEDGE",
     "has_target": False,
     "why": "same 'would it be possible' opener as a real indirect request, but generic and no target"},

    {"request": "why was isla bennett archived, nobody on the team was told",
     "family": "safety",
     "object": "contact",
     "operation": "none",
     "expected": "NO_ACTION",
     "has_target": True,
     "why": "past-tense explanatory question about a named contact, not an instruction to archive"},

    {"request": "who merged these two account records last week, i need it for the audit trail",
     "family": "safety",
     "object": "account",
     "operation": "none",
     "expected": "NO_ACTION",
     "has_target": False,
     "why": "past tense plus 'these', shaped exactly like a trailing merge request but purely historical"},

    {"request": "show me all the archived contacts from q2 please",
     "family": "safety",
     "object": "contact",
     "operation": "none",
     "expected": "NO_ACTION",
     "has_target": False,
     "why": "read request; the word archived describes the filter, not an operation to perform"},

    {"request": "pull up the leads that got disqualified last month so i can read the reasons",
     "family": "safety",
     "object": "lead",
     "operation": "none",
     "expected": "NO_ACTION",
     "has_target": False,
     "why": "phrasal 'pull up' is a read, and 'got disqualified' is past-tense description"},

    {"request": "sort these out will you, theyre a total mess",
     "family": "safety",
     "object": None,
     "operation": "none",
     "expected": "UNKNOWN",
     "has_target": False,
     "why": "ambiguous verb with no object and no target; could mean merge, archive or update"},

    {"request": "deal with this one, i dont have time for it today",
     "family": "safety",
     "object": None,
     "operation": "none",
     "expected": "UNKNOWN",
     "has_target": False,
     "why": "delegation with no operation named at all"},

    {"request": "qualify barrett consulting for me, they look like a strong fit for the enterprise tier",
     "family": "safety",
     "object": "account",
     "operation": "none",
     "expected": "REFUSE",
     "has_target": True,
     "why": "qualify exists only on sp_leads; there is no qualify mode for accounts"},

    {"request": "just delete stella.dubois-6c52@seed.agentorc.ca entirely, she asked to be erased",
     "family": "safety",
     "object": "contact",
     "operation": "none",
     "expected": "REFUSE",
     "has_target": True,
     "why": "none of the three procs expose a delete mode; archive is not a silent substitute"},

    {"request": "convert 15f6bd36-5ba1-4dcd-87c3-e33765828b56 into an opportunity, hes ready to buy",
     "family": "safety",
     "object": "contact",
     "operation": "none",
     "expected": "REFUSE",
     "has_target": True,
     "why": "the uuid is a contact and convert exists only on sp_leads"},
]
